version: '3.8'

services:
  ### REDIS

  redis-node1:
    image: redis:7-alpine                         
    container_name: redis-node1
    restart: always                                
    ports:
      - "6379:6379"                                 # Порт для клиентских подключений (приложения)
    # - "16379:16379"                               # Порт для внутреннего общения кластера (bus port), нужно открыть, если есть подключение с другого докера или хотим мониторить
    networks:
      - app-network                                
    volumes:
      - redis-node1-data:/data                     
    command: >
      redis-server
      --port 6379                                 
      --cluster-enabled yes                        
      --cluster-config-file nodes.conf            
      --cluster-node-timeout 5000                  
      --appendonly yes                             
      --bind 0.0.0.0                                
     # --requirepass ${REDIS_PASSWORD:-redis123}     # Пароль для подключения клиентов
     # --masterauth ${REDIS_PASSWORD:-redis123}      # Пароль для подключения реплик к мастеру
     # --port 6379                                   # Порт внутри контейнера для клиентов
     # --cluster-enabled yes                         # Включаем режим кластера (шардирование)
     # --cluster-config-file nodes.conf              # Файл для хранения конфигурации кластера (создается авто)
     # --cluster-node-timeout 5000                   # Таймаут для определения недоступности ноды (мс)
     # --appendonly yes                              # Сохранять данные на диск (persistence)
     # --bind 0.0.0.0                                # Слушать все сетевые интерфейсы (для Docker)
      
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s                                 
      timeout: 3s                                  
      retries: 5                                   

  redis-node2:
    image: redis:7-alpine
    container_name: redis-node2
    restart: always
    ports:
      - "6380:6379"                                 
    networks:
      - app-network
    volumes:
      - redis-node2-data:/data
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node3:
    image: redis:7-alpine
    container_name: redis-node3
    restart: always
    ports:
      - "6381:6379"
    networks:
      - app-network
    volumes:
      - redis-node3-data:/data
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node4:
    image: redis:7-alpine
    container_name: redis-node4
    restart: always
    ports:
      - "6382:6379"
    networks:
      - app-network
    volumes:
      - redis-node4-data:/data
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node5:
    image: redis:7-alpine
    container_name: redis-node5
    restart: always
    ports:
      - "6383:6379"
    networks:
      - app-network
    volumes:
      - redis-node5-data:/data
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node6:
    image: redis:7-alpine
    container_name: redis-node6
    restart: always
    ports:
      - "6384:6379"
    networks:
      - app-network
    volumes:
      - redis-node6-data:/data
    command: >
      redis-server
      --port 6379
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --bind 0.0.0.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # ===== REDIS CLUSTER INITIALIZER =====
  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    networks:
      - app-network
    depends_on:
      redis-node1:
        condition: service_healthy
      redis-node2:
        condition: service_healthy
      redis-node3:
        condition: service_healthy
      redis-node4:
        condition: service_healthy
      redis-node5:
        condition: service_healthy
      redis-node6:
        condition: service_healthy
    volumes: 
      - ./init-scripts/redis:/scripts:ro   
    entrypoint: ["/bin/sh", "/scripts/init-cluster.sh"]
    restart: "no"

  ## MONGO CONFIGURATION ##

  configSrv1:
    image:  dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv1 
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - config1-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet", "config_server", # конфиг сервер должен запускаться в режиме репликации, но мы тут задаем replica-set  config_server с одним элемнтом для простоты
        "--bind_ip_all", 
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  configSrv2:
    image:  dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv2 
    restart: always
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - config2-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet", "config_server", # конфиг сервер должен запускаться в режиме репликации, но мы тут задаем replica-set  config_server с одним элемнтом для простоты
        "--bind_ip_all", 
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  configSrv3:
    image:  dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv3 
    restart: always
    ports:
      - "27019:27017"
    networks:
      - app-network
    volumes:
      - config3-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet", "config_server", # конфиг сервер должен запускаться в режиме репликации, но мы тут задаем replica-set  config_server с одним элемнтом для простоты
        "--bind_ip_all", 
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5


  shard1-node1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-node1
    restart: always
    ports:
      - "27020:27018"
    networks:
      - app-network
    volumes:
      - shard1-data1:/data/db
    command:
      [
        "--shardsvr",  # запуск в режиме шардинга
        "--replSet",
        "shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  shard1-node2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-node2
    restart: always
    ports:
      - "27021:27018"
    networks:
      - app-network
    volumes:
      - shard1-data2:/data/db
    command:
      [
        "--shardsvr",  # запуск в режиме шардинга
        "--replSet",
        "shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  shard1-node3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-node3
    restart: always
    ports:
      - "27022:27018"
    networks:
      - app-network
    volumes:
      - shard1-data3:/data/db
    command:
      [
        "--shardsvr",  # запуск в режиме шардинга
        "--replSet",
        "shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  shard2-node1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-node1
    restart: always
    ports:
      - "27023:27019"
    networks:
      - app-network
    volumes:
      - shard2-data1:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  shard2-node2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-node2
    restart: always
    ports:
      - "27024:27019"
    networks:
      - app-network
    volumes:
      - shard2-data2:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5

  shard2-node3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-node3
    restart: always
    ports:
      - "27025:27019"
    networks:
      - app-network
    volumes:
      - shard2-data3:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5
  
  mongos_router1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router1
    restart: always
    ports:
      - "27030:27020"
    networks:
      - app-network
    command:
      [
        "mongos",  # обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv1:27017,configSrv2:27017,configSrv3:27017",  # передача данных сервера конфигурации
        "--bind_ip_all", # слушаем все сетевые интерфейсы контейнера (без этого слушаем только localhost)
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
      retries: 5
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1-node1:
        condition: service_healthy
      shard1-node2:
        condition: service_healthy
      shard1-node3:
        condition: service_healthy
      shard2-node1:
        condition: service_healthy
      shard2-node2:
        condition: service_healthy
      shard2-node3:
        condition: service_healthy

  mongos_router2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router2
    restart: always
    ports:
      - "27031:27020"
    networks:
      - app-network
    command:
      [
        "mongos",
        "--configdb", "config_server/configSrv1:27017,configSrv2:27017,configSrv3:27017",
        "--bind_ip_all",
        "--port", "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      retries: 10
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1-node1:
        condition: service_healthy
      shard1-node2:
        condition: service_healthy
      shard1-node3:
        condition: service_healthy
      shard2-node1:
        condition: service_healthy
      shard2-node2:
        condition: service_healthy
      shard2-node3:
        condition: service_healthy

  mongos_router3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router3
    restart: always
    ports:
      - "27032:27020"
    networks:
      - app-network
    command:
      [
        "mongos",
        "--configdb", "config_server/configSrv1:27017,configSrv2:27017,configSrv3:27017",
        "--bind_ip_all",
        "--port", "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      retries: 10
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1-node1:
        condition: service_healthy
      shard1-node2:
        condition: service_healthy
      shard1-node3:
        condition: service_healthy
      shard2-node1:
        condition: service_healthy
      shard2-node2:
        condition: service_healthy
      shard2-node3:
        condition: service_healthy

  mongo_init_replicas:
    container_name: mongo_init_replicas
    volumes:
      - ./init-scripts/mongo/init-replicas:/scripts:ro
    environment:
      - DB_NAME=mobile_world
      - COLLECTION_NAME=users
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1-node1:
        condition: service_healthy
      shard1-node2:
        condition: service_healthy
      shard1-node3:
        condition: service_healthy
      shard2-node1:
        condition: service_healthy
      shard2-node2:
        condition: service_healthy
      shard2-node3:
        condition: service_healthy
    networks:
      - app-network
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]
    restart: "no"

  mongo_configure_cluster:
    container_name: mongo_configure_cluster
    volumes:
      - ./init-scripts/mongo/configure-cluster:/scripts:ro  #перемещение файлов из ./init-scripts/mongo/configure-cluster в директорию /scripts контейнера + все файлы в readonly режиме (:ro)
    environment:
      - DB_NAME=mobile_world
      - COLLECTION_NAME=users
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on:
      mongos_router1:
        condition: service_healthy
      mongos_router2:
        condition: service_healthy
      mongos_router3:
        condition: service_healthy
    networks:
      - app-network
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]
    restart: "no"

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      mongos_router1:
        condition: service_healthy
      mongos_router2:
        condition: service_healthy
      mongos_router3:
        condition: service_healthy
      redis-node1:
        condition: service_healthy
      redis-node2:
        condition: service_healthy
      redis-node3:
        condition: service_healthy
      redis-node4:
        condition: service_healthy
      redis-node5:
        condition: service_healthy
      redis-node6:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      MONGODB_URL: "mongodb://mongos_router1:27020,mongos_router2:27020,mongos_router3:27020"
      MONGODB_DATABASE_NAME: "mobile_world"
      REDIS_URL: "redis://redis-node1:6379,redis-node2:6379,redis-node3:6379,redis-node4:6379,redis-node5:6379,redis-node6:6379"


networks:
  app-network:
    driver: bridge

volumes:
  config1-data:
  config2-data:
  config3-data:
  shard1-data1:
  shard1-data2:
  shard1-data3:
  shard2-data1:
  shard2-data2:
  shard2-data3:
  redis-node1-data:
  redis-node2-data:
  redis-node3-data:
  redis-node4-data:
  redis-node5-data:
  redis-node6-data: